## The following functions satisfy assigment2 in the Coursera
## R programming class from John Hopkins university


## functions do

## makeCacheMatrix will create a matrix and cache the matrix inverse

makeCacheMatrix <- function(x = matrix()) {
  matrixInverseCache <- NULL
  set <-function(y){
    x <<- y
    matrixInverseCache <<- NULL
  }
  get <- function() x
  setMatrixInverse <- function(solve) matrixInverseCache <<- solve
  getMatrixInverse <- function() matrixInverseCache
  list(set = set, get = get,
       setMatrixInverse = setMatrixInverse,
       getMatrixInverse = getMatrixInverse)

}


## cacheSolve will use the matrix generated by makeCacheMatrix and use
## inverse matrix if cached otherwise it will calculate and update the cache

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  m <- x$getMatrixInverse()
  if(!is.null(m)){
    message("Getting matrix Inverse from cache...")
    return(m)
  }
  data <- x$get()
  m <- solve(data,...)
  x$setMatrixInverse(m)
  m
}
